import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = Path("scripts/render_guideline_artifacts.py")
CANONICAL_SOURCE = Path(
    "plugins/andrej-karpathy-skills/content/karpathy-guidelines.md"
)
GENERATED_FILES = [
    Path("plugins/andrej-karpathy-skills/skills/karpathy-guidelines/SKILL.md"),
    Path("skills/karpathy-guidelines/SKILL.md"),
    Path("CLAUDE.md"),
    Path(".cursor/rules/karpathy-guidelines.mdc"),
]
GENERATED_NOTICE = (
    "<!-- Generated by scripts/render_guideline_artifacts.py; do not edit directly. -->"
)


class RenderGuidelineArtifactsTest(unittest.TestCase):
    def copy_repo(self) -> Path:
        tempdir = tempfile.mkdtemp(prefix="karpathy-skill-render-")
        temp_root = Path(tempdir) / "repo"
        shutil.copytree(
            REPO_ROOT,
            temp_root,
            ignore=shutil.ignore_patterns(
                ".git",
                ".worktrees",
                "__pycache__",
                "*.pyc",
                ".DS_Store",
            ),
        )
        return temp_root

    def run_script(self, repo_root: Path, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["python3", str(repo_root / SCRIPT_PATH), *args],
            cwd=repo_root,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_render_updates_all_generated_artifacts_from_canonical_source(self) -> None:
        repo_root = self.copy_repo()
        source_path = repo_root / CANONICAL_SOURCE
        source_path.write_text(
            source_path.read_text()
            + "\n\n## Drift Marker\n\nRender this exact sentence into every generated artifact.\n",
            encoding="utf-8",
        )

        result = self.run_script(repo_root)

        self.assertEqual(
            result.returncode,
            0,
            msg=f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}",
        )

        for relative_path in GENERATED_FILES:
            content = (repo_root / relative_path).read_text(encoding="utf-8")
            self.assertIn(GENERATED_NOTICE, content, msg=str(relative_path))
            self.assertIn(
                "Render this exact sentence into every generated artifact.",
                content,
                msg=str(relative_path),
            )

            if relative_path.name == "SKILL.md":
                self.assertTrue(
                    content.startswith(
                        "---\n"
                        "name: karpathy-guidelines\n"
                        "description: Behavioral guidelines to reduce common LLM coding mistakes."
                    ),
                    msg=str(relative_path),
                )

            if relative_path.suffix == ".mdc":
                self.assertTrue(
                    content.startswith(
                        "---\n"
                        "description: Behavioral guidelines to reduce common LLM coding mistakes."
                    ),
                    msg=str(relative_path),
                )

    def test_check_mode_fails_when_generated_artifact_drifts(self) -> None:
        repo_root = self.copy_repo()
        render_result = self.run_script(repo_root)
        self.assertEqual(
            render_result.returncode,
            0,
            msg=f"stdout:\n{render_result.stdout}\n\nstderr:\n{render_result.stderr}",
        )

        drifted_file = repo_root / "CLAUDE.md"
        drifted_file.write_text(
            drifted_file.read_text(encoding="utf-8") + "\nManual edit.\n",
            encoding="utf-8",
        )

        check_result = self.run_script(repo_root, "--check")

        self.assertNotEqual(check_result.returncode, 0)
        self.assertIn("CLAUDE.md", check_result.stdout + check_result.stderr)


if __name__ == "__main__":
    unittest.main()
