#!/usr/bin/env python3
"""Render shared Karpathy guideline content into target-specific artifacts."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


GENERATED_NOTICE = (
    "<!-- Generated by scripts/render_guideline_artifacts.py; do not edit directly. -->"
)
CANONICAL_SOURCE = Path("skills/karpathy-guidelines/content.md")
SKILL_OUTPUT = Path("skills/karpathy-guidelines/SKILL.md")
CLAUDE_MD = Path("CLAUDE.md")
CURSOR_RULE = Path(".cursor/rules/karpathy-guidelines.mdc")
SKILL_DESCRIPTION = (
    "Behavioral guidelines to reduce common LLM coding mistakes. "
    "Use when writing, reviewing, or refactoring code to avoid overcomplication, "
    "make surgical changes, surface assumptions, and define verifiable success criteria."
)
COMMON_INTRO = (
    "Behavioral guidelines to reduce common LLM coding mistakes, derived from "
    "[Andrej Karpathy's observations](https://x.com/karpathy/status/2015883857489522876) "
    "on LLM coding pitfalls."
)
CLAUDE_INTRO = (
    "Behavioral guidelines to reduce common LLM coding mistakes. "
    "Merge with project-specific instructions as needed."
)
CLAUDE_FOOTER = (
    "---\n\n"
    "**These guidelines are working if:** fewer unnecessary changes in diffs, "
    "fewer rewrites due to overcomplication, and clarifying questions come before "
    "implementation rather than after mistakes."
)


def load_canonical_body(repo_root: Path) -> str:
    source_path = repo_root / CANONICAL_SOURCE
    return source_path.read_text(encoding="utf-8").strip()


def join_sections(*sections: str) -> str:
    return "\n\n".join(section.strip() for section in sections if section.strip()) + "\n"


def join_lines(*lines: str) -> str:
    return "\n".join(line.rstrip() for line in lines if line is not None)


def build_skill_document(body: str) -> str:
    frontmatter = join_lines(
        "---",
        "name: karpathy-guidelines",
        f"description: {SKILL_DESCRIPTION}",
        "license: MIT",
        "---",
    )
    return join_sections(
        frontmatter,
        GENERATED_NOTICE,
        "# Karpathy Guidelines",
        COMMON_INTRO,
        body,
    )


def build_claude_document(body: str) -> str:
    return join_sections(
        GENERATED_NOTICE,
        "# CLAUDE.md",
        CLAUDE_INTRO,
        body,
        CLAUDE_FOOTER,
    )


def build_cursor_rule(body: str) -> str:
    frontmatter = join_lines(
        "---",
        f"description: {SKILL_DESCRIPTION}",
        "alwaysApply: true",
        "---",
    )
    return join_sections(
        frontmatter,
        GENERATED_NOTICE,
        "# Karpathy behavioral guidelines",
        CLAUDE_INTRO,
        body,
        CLAUDE_FOOTER,
    )


def render_outputs(repo_root: Path) -> dict[Path, str]:
    body = load_canonical_body(repo_root)
    skill_document = build_skill_document(body)
    return {
        SKILL_OUTPUT: skill_document,
        CLAUDE_MD: build_claude_document(body),
        CURSOR_RULE: build_cursor_rule(body),
    }


def write_outputs(repo_root: Path, outputs: dict[Path, str]) -> list[Path]:
    updated_paths: list[Path] = []
    for relative_path, content in outputs.items():
        destination = repo_root / relative_path
        current_content = (
            destination.read_text(encoding="utf-8") if destination.exists() else None
        )
        if current_content == content:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        updated_paths.append(relative_path)
    return updated_paths


def find_drift(repo_root: Path, outputs: dict[Path, str]) -> list[Path]:
    drifted_paths: list[Path] = []
    for relative_path, expected_content in outputs.items():
        destination = repo_root / relative_path
        current_content = (
            destination.read_text(encoding="utf-8") if destination.exists() else None
        )
        if current_content != expected_content:
            drifted_paths.append(relative_path)
    return drifted_paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render shared Karpathy guideline content into derived artifacts."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any generated artifact is out of date.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    outputs = render_outputs(repo_root)

    if args.check:
        drifted_paths = find_drift(repo_root, outputs)
        if drifted_paths:
            print("Generated artifacts are out of date:")
            for path in drifted_paths:
                print(f"- {path.as_posix()}")
            return 1
        print("Generated artifacts are up to date.")
        return 0

    updated_paths = write_outputs(repo_root, outputs)
    if updated_paths:
        print("Updated generated artifacts:")
        for path in updated_paths:
            print(f"- {path.as_posix()}")
    else:
        print("Generated artifacts already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
